# Generated by Django 5.1.2 on 2024-10-20 22:09

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший'),
        ),
        migrations.AlterField(
            model_name='userreferralcode',
            name='code',
            field=models.CharField(default=apps.users.models.generate_referral_code, max_length=6, unique=True, verbose_name='Реферальный код'),
        ),
    ]
