# Generated by Django 5.1.2 on 2024-10-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invited_by_alter_userreferralcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferralcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
