# Generated by Django 5.1.2 on 2024-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_user_password_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code_used',
            field=models.BooleanField(default=False),
        ),
    ]
