# Generated by Django 5.1.2 on 2024-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_invite_code_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite_code_used',
        ),
        migrations.AddField(
            model_name='userreferralcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
